fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

lia_user:
    resource: "@LiaCmsUserBundle/Resources/config/routing/user.yml"
    prefix: /user